import image from "./assets/dummy.jpeg";

const data = [
  {
    id: 1,
    img: image,
    name: "Vinaya Patil",
    email: "vinaya123@gmail.com",
    phone: "1234567890",
    country: "India",
    city: "Bengaluru",
    type: "type1",
    bank: "ICICI",
    accountNo: "879076",
    subEmail: "patil@gmail.com",
    subBank: "ICICI-1",
    subAccountNo: "76889",
    active: true,
    fundDetails: {
      underManagement: 2000000,
      inventedValue: 150000,
      curPorfolioValue: 2360000,
      growthRatio: 24,
      investedNumOFComp: 6,
      primaryDeals: 4,
      secondaryDeals: 8,
    },
  },
  {
    id: 2,
    img: image,
    name: "XYZ",
    email: "xyz123@gmail.com",
    phone: "1234567890",
    country: "India",
    city: "Bengaluru",
    type: "type1",
    bank: "ICICI",
    accountNo: "879076",
    subEmail: "patil@gmail.com",
    subBank: "ICICI-1",
    subAccountNo: "76889",
    active: false,
    fundDetails: {
      underManagement: 2000000,
      inventedValue: 150000,
      curPorfolioValue: 2360000,
      growthRatio: 24,
      investedNumOFComp: 6,
      primaryDeals: 4,
      secondaryDeals: 8,
    },
  },

  {
    id: 3,
    img: image,
    name: "abc",
    email: "abc123@gmail.com",
    phone: "1234567890",
    country: "India",
    city: "Bengaluru",
    type: "type1",
    bank: "ICICI",
    accountNo: "879076",
    subEmail: "patil@gmail.com",
    subBank: "ICICI-1",
    subAccountNo: "76889",
    active: true,
    // fundDetails: {
    //   underManagement: 2000000,
    //   inventedValue: 150000,
    //   curPorfolioValue: 2360000,
    //   growthRatio: 24,
    //   investedNumOFComp: 6,
    //   primaryDeals: 4,
    //   secondaryDeals: 8,
    // },
  },
  {
    id: 4,
    img: image,
    name: "XYZ",
    email: "xyz123@gmail.com",
    phone: "1234567890",
    country: "India",
    city: "Bengaluru",
    type: "type1",
    bank: "ICICI",
    accountNo: "879076",
    subEmail: "patil@gmail.com",
    subBank: "ICICI-1",
    subAccountNo: "76889",
    active: false,
    fundDetails: {
      underManagement: 2000000,
      inventedValue: 150000,
      curPorfolioValue: 2360000,
      growthRatio: 24,
      investedNumOFComp: 6,
      primaryDeals: 4,
      secondaryDeals: 8,
    },
  },
];

export default data;
